### ISSUE TITLE
gimme scan produces no results when scanning many regions

### ISSUE THREAD

**Issue by LKremer** [vanheeringen-lab/gimmemotifs#152]
**gimme scan produces no results when scanning many regions**
I tried to scan a large ChIP-seq file with gimme scan, but somehow I got zero hits. I used the following command:
`gimme scan Oth.ALL.05.Sox2.AllCell.bed -g mm10 -p examples/example.pfm`
I get only this output when the script is finished:
```
# GimmeMotifs version 0.15.1
# Input: Oth.ALL.05.Sox2.AllCell.bed
# Motifs: examples/example.pfm
# FPR: 0.01 (mm10)
# Scoring: logodds score
2020-10-28 10:49:22,893 - INFO - determining FPR-based threshold
```
The script is running for quite some time, so I think the scanning is happening. Maybe it's a silent crash that prevents the output from being written.
When I take only the first 1000 lines of the bed file, everything works flawlessly:
`head -n 1000 Oth.ALL.05.Sox2.AllCell.bed > Oth.ALL.05.Sox2.AllCell_head1000.bed`
`gimme scan Oth.ALL.05.Sox2.AllCell_head1000.bed -g mm10 -p examples/example.pfm`
```
# GimmeMotifs version 0.15.1
# Input: Oth.ALL.05.Sox2.AllCell_head1000.bed
# Motifs: examples/example.pfm
# FPR: 0.01 (mm10)
# Scoring: logodds score
chr1:3676482-3676757    pfmscan misc_feature    236     244     10.69957607887771       +       .       motif_name "AP1" ; motif_instance "ATGAGTCAT"
chr1:4416781-4416972    pfmscan misc_feature    121     134     13.273571109612698      +       .       motif_name "CTCF" ; motif_instance "GCGCCACCTTGTGG"
chr1:4416785-4417017    pfmscan misc_feature    117     130     13.273571109612698      +       .       motif_name "CTCF" ; motif_instance "GCGCCACCTTGTGG"
[truncated...]
```
I don't think it's a problem with my bed file. To be extra sure, I removed all columns except 1-3, I removed all "weird" chromosomes (contigs without proper numbering etc), I sorted it with bedtools sort...
When I split the file into ~20 chunks (one per chromosome), all 20 chunks produce the expected output. So I don't think its a corrupt entry in the bed file, but more the total number of entries that causes the problem.
Here are the first 5 lines of the file:
```
chr1    3005524 3005922
chr1    3005528 3005943
chr1    3023143 3023434
chr1    3042827 3043208
chr1    3042844 3043243
```
The pfm file I used is from the examples directory of gimme, so it should be correct.

**To Reproduce**
1. download a large bed file, e.g. from [https://chip-atlas.org/peak_browser](https://chip-atlas.org/peak_browser)
2. scan it with `gimme scan your_large.bed -g mm10 -p examples/example.pfm`
3. receive empty output file

**Expected behavior**
gimme scan should print hits even when scanning many regions.

**Error logs**
I don't get any errors or crashes, just a result file without hits. Is there any way to access the logs?

**Installation information (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Installation: conda/4.9.0 requests/2.24.0 CPython/3.8.3 Linux/4.15.0-48-generic ubuntu/18.04.4 glibc/2.27
 - Version: GimmeMotifs v0.15.1
 - installed mm10 with genomepy, including annotation

**Additional context**
A workaround is to split my input file into many chunks and scan all of them separately, and merge the results later. This works nicely, but of course it's ugly.

**Comment by simonvh** [comment]
Thanks for the extensive bug report! I'll look into it.

**Comment by fgualdr** [comment]
Hi am am actually getting the same issue.
Blank .bed output even setting -f to 0.9

**Comment by simonvh** [comment]
@LKremer I think I have fixed the issue, but I can't find how to download a specific peak file from ChIP-atlas. How many regions were in the file that failed for you?

**Comment by LKremer** [comment]
Hi @simonvh ,
thanks for taking your time to fix this issue! I agree, the ChIP-atlas interface is a little enigmatic. [This](http://dbarchive.biosciencedbc.jp/kyushu-u/mm10/assembled/Oth.ALL.05.Sox2.AllCell.bed) is the file I used and it has over half a million lines (I don't have the original file anymore but I'll download and check the line count again and edit this comment).
But what I can already say is that the problem persists even when I only take the first 30000 lines of the file:
```
lukas@notebook:~$ head -n 30000 Oth.ALL.05.Sox2.AllCell.bed > Oth.ALL.05.Sox2.AllCell_head30k.bed`
lukas@notebook:~$ gimme scan Oth.ALL.05.Sox2.AllCell_head30k.bed -g mm10 -p examples/example.pfm
# GimmeMotifs version 0.15.1
# Input: Oth.ALL.05.Sox2.AllCell_head30k.bed
# Motifs: examples/example.pfm
# FPR: 0.01 (mm10)
# Scoring: logodds score
2020-11-13 13:21:46,132 - INFO - determining FPR-based threshold
lukas@notebook:~$
```
I also tried sorting the file and removing all columns that aren't necessary (only keeping chrom, start, end) but to no avail.

**Comment by fgualdr** [comment]
How to get the fix on a Honda installed version? I still cannot figure out how to make gimme to scan a BED (with about 30000 peaks) using a single CTCF motif. Can only process 2000 at a time.

**Comment by simonvh** [comment]
I am really sorry, but I do not yet have a complete handle on the issue (we routinely scan 10-50,000 peaks with ~1700 motifs without problems, and have scanned 1+ million regions as well), but if you want you can test the provisional fix by installing the dev version of gimme.

In your activated conda environment:

```
# make sure you have pip for this environment
conda install pip
# install dev version with pip
pip install git+https://github.com/vanheeringen-lab/gimmemotifs@3972d06
```

Let me know if this works for you. If this fixes the issue on your side I would be happy to release a new bugfix version on conda.

**Comment by fgualdr** [comment]
Unfortunately the link https://github.com/vanheeringen-lab/gimmemotifs@3972d06 seems to have issues.

**Comment by simonvh** [comment]
Sorry, too quick.
Command should be `pip install git+https://github.com/vanheeringen-lab/gimmemotifs.git@3972d06`

**Comment by simonvh** [comment]
@fgualdr does this fix the problem for you?

**Comment by fgualdr** [comment]
Unfortunately I had issues to install the "gimmemotifs.git@3972d06" version within my gimme environment and afterward I got sucked into other things to do so didn't tested it - need to check why I am unable to pip install that.
As soon as I get somethings I'll post
Thanks

**Comment by simonvh** [comment]
Based on our testing, scanning should now work for large files (we have scanned up to 4 million regions). Feel free to open if you still encounter this issue.
